// Override an _alarm function generated by emscripten.
// We store handles for the callback so we can cancle the timeouts on runtime exit
var timeoutHandles = [];
function _alarm(seconds) {
    console.log("new alarm called");
    var handle = setTimeout(function () {
        if (__sigalrm_handler) dynCall_vi(__sigalrm_handler, 0);
    }, seconds * 1000);
    timeoutHandles.push(handle);
}

function clearAlarms(){
    for(var i=0; i<timeoutHandles.length; i++){
        clearTimeout(timeoutHandles[i]);
    }
}

// Module.preRun is an array of functions called before the module is initalized.
Module.postRun = Module.postRun || [];
Module.postRun.push(clearAlarms);
