/**
 * This file adds some functions to the CommonJS module generated by emscripten.
 * The file should be included in the build by adding the --post-js argument to emcc.
 */

// We store handles to the alarm timeouts so we can cancel them on runtime exit.
let timeoutHandles = [];

// Override the function _alarm generated by emscripten.
function _alarm(seconds) {
	timeoutHandles.push(setTimeout(() => {
		if (__sigalrm_handler) dynCall_vi(__sigalrm_handler, 0);
	}, seconds * 1000));
}

// Module.postRun is an array of functions called after the module is initalized.
Module.postRun = Module.postRun || [];
Module.postRun.push(clearAlarms);

function clearAlarms() {
	for (let i = 0, n = timeoutHandles.length; i < n; i++) {
		clearTimeout(timeoutHandles[i]);
	}
}
